import kotlinx.serialization.Serializable

@Serializable
data class Empleado(
	val cantidad_ingresos: String? = null,
	val identificacion_tipo: Int? = null,
	val estado: Int? = null,
	val codusuario_modifica: String? = null,
	val porcentaje_reteica: String? = null,
	val o_retieneica: String? = null,
	val fecha_nacimiento: String? = null,
	val foto_perfil: String? = null,
	val fecha_creacion: String? = null,
	val fecha_modificacion: String? = null,
	val empleado_sucursal: String? = null,
	val nombres: String? = null,
	val nombre_tributario: String? = null,
	val password: String? = null,
	val naturaleza: String? = null,
	val o_autoretenedor: String? = null,
	val empleado_activo: Int? = null,
	val direccion_alternativa: String? = null,
	val genero: Int? = null,
	val dias_compras: String? = null,
	val porcentaje_dsctofijo_1: String? = null,
	val o_grancontribuyente: String? = null,
	val porcentaje_dsctofijo_4: String? = null,
	val cargo: String? = null,
	val regimen: String? = null,
	val telefono_movil: String? = null,
	val email: String? = null,
	val porcentaje_dsctofijo_2: String? = null,
	val porcentaje_dsctofijo_3: String? = null,
	val apellidos: String? = null,
	val codtercero: Int? = null,
	val telefono_fijo: String? = null,
	val cupocredito: String? = null,
	val pinrecargas: String? = null,
	val codigo: String? = null,
	val porcentaje_rfte_compras: String? = null,
	val codciudad: Int? = null,
	val direccion: String? = null,
	val identificacion: String? = null,
	val porcentaje_compras: String? = null,
	val dias_credito: String? = null,
	val tipo_sangre: String? = null,
	val identificacion_expedicion: Int? = null,
	val empleado_bodega: String? = null,
	val codusuario_creador: String? = null,
	val maximo_cupo_compra: String? = null,
	val datos_consignacion: String? = null
)

